### ISSUE TITLE
Github betas are crashing VCV Rack

### ISSUE THREAD

**Issue by pgatt** [ContemporaryInsanity/RacketScience#2]
Hi there, 
Just letting you know - I understand that it is my own fault for downloading betas and building myself from GitHub but in case you weren't aware your recent Github commits build and compile correctly, but when I open Rack on Mac here and go to enter a module name in the module browser, VCV crashes immediately. Feel absolutely free to ignore if that is just because it is a work in progress, also let me know if you want further details.

Regards,
Paul.

**Comment by ContemporaryInsanity** [comment]
Hi Paul,

Thanks for letting me know, further details would be appreciated, stack trace / log file?  Any info at all.
From what you say the module browser displays ok but only crashes once you start typing?  Does it display my modules at the top (if freshly installed)  BEFORE you start typing?

I've no experience of cross platform development, what to watch out for etc.  I am reading & writing binary data, whether the layout of that might cause issues across platforms I don't know but that will be changed to json imminently.  In my experience most browser crashing is often caused by widget trying to access a non existent module while the browser is being populated but I'm pretty sure none of mine do that or it'd crash here too.

This is still very much a work in progress and won't be ready for release for some time, though my new silly sequencer is just about finished and will need doze & mac testers soon.

Thanks once more for the heads up.

Ewen.

**Comment by pgatt** [comment]
Sorry Ewen, correction - I didn't realise before but VCV crashes immediately after hitting enter to bring up the module browser.

I have linked the VCV crash log and the Mac crash report below:

https://www.dropbox.com/s/llz0cb75eo1awrt/Crash%20log.txt?dl=0

https://www.dropbox.com/s/fwwc6mkw4mph3z2/Crash%20report.txt?dl=0

**Comment by ContemporaryInsanity** [comment]
Great, thanks.

The VCV crash log gives me a clue, the mac report less so.

I'll make a few changes and another commit later, will let you know once done.

Cheers.

E.

**Comment by ContemporaryInsanity** [comment]
Hi,

I've added logging to help find what's causing the browser crash.  If you could pull, compile & run the latest and send the resulting log file I'd be very grateful.

E.

**Comment by pgatt** [comment]
https://www.dropbox.com/s/wy91tknclwh1qvl/Racket%20Science%20browser%20crash.txt?dl=0

**Comment by ContemporaryInsanity** [comment]
Thank you.

Could you edit my plugin.json, removing

,
    {
      "slug": "RSVectorVictor",
      "name": "RSVectorVictor",
      "description": "Phase Driven CV Looper",
      "tags": [
        "Recorder",
        "Sequencer"
      ]
    }

from the end, rebuild and see if it still crashes please?

E.

**Comment by pgatt** [comment]
That fixed it Ewen!

**Comment by ContemporaryInsanity** [comment]
Right, so it's definitely a problem with my original, simplest module!  Hmmmm....

I'll have to have a think, nothing immediately obvious.

Are you up for testing it again once I've made changes?

Also, if you'd like to play around with what does work (specifically Fido3 monster sequencer & Reheat) and let me know what you think / report any bugs that'd be great.

Thanks once more.

**Comment by pgatt** [comment]
Yes, that’s fine. Will see how I go today.

**Comment by pgatt** [comment]
Sorry Ewen it's crashing again now that I'm trying again:

https://www.dropbox.com/s/gyryodln6e2v67d/New%20crash%20report.txt?dl=0

**Comment by ContemporaryInsanity** [comment]
Grrrr.

Largely clueless unfortunately.  I'l replace my binary file storage with json today and let you know once I've pushed, really can't think what else it might be.

Thanks for your efforts.

**Comment by ContemporaryInsanity** [comment]
Have replaced binary storage with json if you'd like to give it another try.

If that hasn't worked, is there any other info you can give me?  I've had no similar reports from other mac users (could be that there are no other mac users, it's a niche plugin atm really) and it runs fine on linux.

**Comment by pgatt** [comment]
That seems to have fixed it Ewen, thanks a bunch.

**Comment by ContemporaryInsanity** [comment]
Really!  Fantastic.

Any more issues just shout.

Thanks for your help.

**Comment by pgatt** [comment]
Is Fido the big Phase Sequencer?

**Comment by ContemporaryInsanity** [comment]
Just a do it all (just about) step sequencer that can be driven by phase should you want to.  Still testing, has at least one bug but no show stoppers that I'm aware of.  Feedback welcome.
